In [1]:
import numpy as np 
import pandas as pd

In [3]:
falsy_values=(0 , False, None, '' ,[], {}) 
# all these values are considered as falsy 

In [5]:
any(falsy_values)

False

In [9]:
np.nan   #nan= not a number

nan

In [29]:
a= np.array([1,2,3,np.nan, None, 4] , dtype ='float')
a

array([ 1.,  2.,  3., nan, nan,  4.])

In [13]:
3+ np.nan

nan

In [35]:
b= np.array([1,2,3,np.nan, np.nan, 4])
b

array([ 1.,  2.,  3., nan, nan,  4.])

In [37]:
a.sum()

nan

In [21]:
a.mean()

nan

In [39]:
np.inf

inf

In [41]:
3+np.inf

inf

In [43]:
np.inf/3

inf

In [51]:
b = np.array([1, 2, 3, np.inf, np.nan, 4], dtype=float)
b

array([ 1.,  2.,  3., inf, nan,  4.])

In [53]:
b.sum()

nan

In [3]:
# checking for nan or inf

In [57]:
np.isnan(np.nan)

True

In [59]:
np.isinf(np.inf)

True

In [63]:
np.isfinite(np.inf) , np.isfinite(np.nan)

(False, False)

In [65]:
np.isnan(np.array([1,2,3,np.nan, np.inf, 4]))

array([False, False, False,  True, False, False])

In [67]:
np.isinf(np.array([1,2,3,np.nan, np.inf, 4]))

array([False, False, False, False,  True, False])

In [69]:
# filtering them out

In [ ]:
a= np.array([1,2,3,np.nan, np.nan, 4])

In [71]:
a[~np.isnan(a)]

array([1., 2., 3., 4.])

In [73]:
a[np.isfinite(a)]

array([1., 2., 3., 4.])

In [75]:
a[np.isfinite(a)].sum()

10.0