In [2]:
import sys
import numpy as np

In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [8]:
a= np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [10]:
a[0] ,a[1]

(1, 2)

In [12]:
a[0:]

array([1, 2, 3, 4, 5])

In [14]:
import numpy as np
b= np.array([1.0,2.0,3.0,4.0])

In [16]:
print(b)

[1. 2. 3. 4.]


In [18]:
b[0]


1.0

In [20]:
b[0,1,2]

IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed

In [36]:
b[[0, 1, 2]]

array([1., 2., 3.])

In [38]:
a.dtype


dtype('int32')

In [40]:
b.dtype

dtype('float64')

In [42]:
np.array([5,6,7,8], dtype= float)

array([5., 6., 7., 8.])

In [46]:
d= np.array(['a' ,'b' ,'c'])

In [46]:
d[0]

'a'

In [50]:
d.dtype

dtype('<U1')

In [50]:
c= np.array([{'a' :1}, sys])

In [52]:
c

array([{'a': 1}, <module 'sys' (built-in)>], dtype=object)

In [ ]:
multidimensional array


In [64]:
import numpy as np
A=np.array([
    [1,2,4],
    [5,6,7]])

In [72]:
A



array([[1, 2, 4],
       [5, 6, 7]])

In [70]:
A.shape


(2, 3)

In [74]:
A.ndim

2

In [76]:
A.size

6

In [106]:
import numpy as np

B = np.array([
       [
           [1, 2, 3,11], [4, 5, 6,13]
       ],  # Comma added here
       [
           [7, 8, 9,19 ], [11, 23, 45,21]
       ]
])

print(B)


[[[ 1  2  3 11]
  [ 4  5  6 13]]

 [[ 7  8  9 19]
  [11 23 45 21]]]


In [2]:
b.shape

NameError: name 'b' is not defined

In [108]:
B.shape

(2, 2, 4)

In [110]:
B.ndim

3

In [112]:
B.size

16

In [24]:
import numpy as np 
C= np.array(
    [
    [1,2,3] ,[3,6,7] , [8,9,23] ])

In [26]:
C[0]

array([1, 2, 3])

In [32]:
C

array([[ 1,  2,  3],
       [ 3,  6,  7],
       [ 8,  9, 23]])

In [34]:
C[1,2]

7

In [38]:
C[0:2]

array([[1, 2, 3],
       [3, 6, 7]])

In [30]:
C[0,0]

1

In [42]:
C[0:1 , 0:1]

array([[1]])

In [44]:
C[: , :2]

array([[1, 2],
       [3, 6],
       [8, 9]])

In [48]:
C[:1, :2]

array([[1, 2]])

In [58]:
C[1] = np.array([1 ,1, 1])

In [60]:
print(
C
)

[[ 1  2  3]
 [ 1  1  1]
 [ 8  9 23]]


In [62]:
C[2] =99

In [66]:
C

array([[ 1,  2,  3],
       [ 1,  1,  1],
       [99, 99, 99]])

In [68]:
import numpy as np 

In [70]:
a=np.array([1,2,3,4])

In [72]:
a

array([1, 2, 3, 4])

In [76]:
a.sum()

10

In [84]:
a.mean()

2.5

In [88]:
a.var()

1.25

In [90]:
a.std()

1.118033988749895

In [94]:
import numpy as np 
s= np.array(
    [
    [1,2,3] 
    ,[3,6,7] ,
     [8,9,23] ])

In [96]:
s.sum(axis=0) #vertical sum 

array([12, 17, 33])

In [100]:
s.sum(axis=1) # horizontal sum 

array([ 6, 16, 40])

In [ ]:
s.sum(axis =2) # error because no third dimension

In [106]:
s.std(axis=0)

array([2.94392029, 2.86744176, 8.6409876 ])

In [108]:
import numpy as np

In [123]:
a= np.arange(10)

In [125]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [127]:
a + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [4]:
import numpy as np


In [6]:
a= np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a * 10

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [10]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
 a+=100

In [14]:
a

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [143]:
l = [2,5,7,8]

In [16]:
a

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [145]:
l

[2, 5, 7, 8]

In [147]:
[i* 10 for i in l]

[20, 50, 70, 80]

In [22]:
a= np.arange(4
            )
a


array([0, 1, 2, 3])

In [24]:
b = np.array([6,7,8,9])

In [26]:
a+b 

array([ 6,  8, 10, 12])

In [30]:
a[[ True, True,False ,True]] 
a

array([0, 1, 2, 3])

In [36]:
a[[False]]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 4 but corresponding boolean dimension is 1

In [38]:
b[[ True, True,False ,True]]

array([6, 7, 9])

In [191]:
a= np.arange(4)

In [197]:
a>=1

array([False,  True,  True,  True])

In [199]:
a>=2

array([False, False,  True,  True])

In [209]:
a[a>=2]

array([2, 3])

In [211]:
a.mean()

1.5

In [213]:
a[a >= a.mean()]

array([2, 3])

In [219]:
a[ (a>1) & (a<3)]

array([2])

In [221]:
# LINEAR ALGEBRA

In [42]:
import numpy as np 
c= np.array(
    [
    [1,2,3] ,
        [3,6,7] , 
          [8,9,23] ])
print (c)

[[ 1  2  3]
 [ 3  6  7]
 [ 8  9 23]]


In [239]:
import numpy as np 
f= np.array(
    [
    [13,42,3] ,[23,6,77] , [38,9,3] ])

In [249]:
c.dot(f) # dot product 

array([[ 173,   81,  166],
       [ 443,  225,  492],
       [1185,  597,  786]])

In [251]:
c @ f # cross product 

array([[ 173,   81,  166],
       [ 443,  225,  492],
       [1185,  597,  786]])

In [253]:
c.  # transpose 

array([[ 1,  3,  8],
       [ 2,  6,  9],
       [ 3,  7, 23]])

In [255]:
c.T @ f

array([[ 386,  132,  258],
       [ 506,  201,  495],
       [1074,  375,  617]])

In [6]:
import numpy as np
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
import numpy as np 

In [20]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [24]:
np.linspace(0 ,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [26]:
np.linspace(0 ,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [36]:
np.linspace(0,1,20,False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [40]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [42]:
np.zeros(3)

array([0., 0., 0.])

In [46]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [54]:
np.zeros((3, 3), dtype=int)


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [56]:
np.ones(3)

array([1., 1., 1.])